//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Reporting.WebForms;

namespace BT_KimMex.Views.Shared.ReportController
{


    public partial class MRreport
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        private global::Microsoft.Reporting.WebForms.ReportViewer reportViewer1;

        protected ReportViewer ReportViewer1
        {
            get
            {
                return reportViewer1;
            }

            set
            {
                reportViewer1 = value;
            }
        }
    }
}
