//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_OrderAandR
    {
        public int Purchase_order_id { get; set; }
        public string purchase_oder_number { get; set; }
        public string Item_request_id { get; set; }
        public string Purchar_Number { get; set; }
        public System.DateTime Create_date { get; set; }
        public string status { get; set; }
        public Nullable<bool> active { get; set; }
        public string supplier_id { get; set; }
        public string checked_by { get; set; }
        public System.DateTime checked_date { get; set; }
        public System.DateTime Update_Date { get; set; }
        public string Update_by { get; set; }
        public string Upprove_by { get; set; }
        public System.DateTime Uprove_date { get; set; }
        public string rejected_by { get; set; }
        public System.DateTime rejected_date { get; set; }
        public string Action { get; set; }
    }
}
