//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_boq_detail2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_boq_detail2()
        {
            this.tb_boq_detail3 = new HashSet<tb_boq_detail3>();
        }
    
        public string boq_detail2_id { get; set; }
        public string boq_detail1_id { get; set; }
        public string item_type_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string remark { get; set; }
    
        public virtual tb_boq_detail1 tb_boq_detail1 { get; set; }
        public virtual tb_product_category tb_product_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_boq_detail3> tb_boq_detail3 { get; set; }
    }
}
