//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_error_log
    {
        public string error_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string class_name { get; set; }
        public string method_name { get; set; }
        public string information_type { get; set; }
        public string exception { get; set; }
        public string message { get; set; }
    }
}
