//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_history_issue_qty
    {
        public string history_issue_qty_id { get; set; }
        public string inventory_detail_id { get; set; }
        public Nullable<decimal> issue_qty { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<bool> status { get; set; }
        public string updated_by { get; set; }
    }
}
