//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_item_quote_attachment
    {
        public string quote_attachment_id { get; set; }
        public string quote_attachment_name { get; set; }
        public string quote_attachment_extension { get; set; }
        public string quote_attachment_part { get; set; }
        public string quote_attachment_ref_id { get; set; }
    
        public virtual tb_quote_detail tb_quote_detail { get; set; }
    }
}
