//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_inventory_detail
    {
        public string inventory_detail_id { get; set; }
        public string inventory_ref_id { get; set; }
        public string inventory_item_id { get; set; }
        public string inventory_warehouse_id { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public string remark { get; set; }
        public string supplier_id { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> previous_quantity { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public string item_status { get; set; }
        public string invoice_number { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public string inventory_type { get; set; }
        public Nullable<decimal> remain_quantity { get; set; }
        public string reason { get; set; }
        public Nullable<int> ordering_number { get; set; }
    }
}
