//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ir_detail2
    {
        public string ir_detail2_id { get; set; }
        public string ir_detail1_id { get; set; }
        public string ir_item_id { get; set; }
        public string ir_item_unit { get; set; }
        public Nullable<decimal> ir_qty { get; set; }
        public Nullable<bool> is_approved { get; set; }
        public Nullable<decimal> approved_qty { get; set; }
        public string reason { get; set; }
        public string remark { get; set; }
        public Nullable<decimal> remain_qty { get; set; }
        public string item_status { get; set; }
        public Nullable<int> ordering_number { get; set; }
        public Nullable<bool> is_po { get; set; }
    
        public virtual tb_ir_detail1 tb_ir_detail1 { get; set; }
        public virtual tb_product tb_product { get; set; }
    }
}
