//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_item_blocking_detail
    {
        public string item_blocking_detail_id { get; set; }
        public string item_blocking_id { get; set; }
        public string warehouse_id { get; set; }
        public Nullable<System.DateTime> item_blocking_date { get; set; }
        public string item_id { get; set; }
        public Nullable<bool> is_block { get; set; }
        public Nullable<decimal> block_qty { get; set; }
        public Nullable<bool> active { get; set; }
        public string remark { get; set; }
    }
}
