//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_mr_cut_off_detail
    {
        public string cut_off_detail_id { get; set; }
        public string cut_off_id { get; set; }
        public string item_id { get; set; }
        public string item_unit_id { get; set; }
        public Nullable<decimal> material_request_qty { get; set; }
        public Nullable<decimal> cut_off_qty { get; set; }
        public string cut_off_reason { get; set; }
        public string item_status { get; set; }
        public string approval_comment { get; set; }
    
        public virtual tb_mr_cut_off tb_mr_cut_off { get; set; }
    }
}
