//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_mr_cut_off
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_mr_cut_off()
        {
            this.tb_mr_cut_off_detail = new HashSet<tb_mr_cut_off_detail>();
        }
    
        public string mr_cut_off_id { get; set; }
        public string material_request_id { get; set; }
        public string mr_cut_off_number { get; set; }
        public string mr_cut_off_status { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> approved_at { get; set; }
        public string approved_by { get; set; }
        public string approved_comment { get; set; }
    
        public virtual tb_item_request tb_item_request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_mr_cut_off_detail> tb_mr_cut_off_detail { get; set; }
    }
}
