//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_mr_related_status
    {
        public int mr_status_id { get; set; }
        public string mr_id { get; set; }
        public string po_status { get; set; }
        public string st_status { get; set; }
        public string tw_status { get; set; }
        public Nullable<bool> active { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
