//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_multiple_uom
    {
        public string uom_id { get; set; }
        public string product_id { get; set; }
        public string uom1_id { get; set; }
        public Nullable<decimal> uom1_qty { get; set; }
        public string uom2_id { get; set; }
        public Nullable<decimal> uom2_qty { get; set; }
        public string uom3_id { get; set; }
        public Nullable<decimal> uom3_qty { get; set; }
        public string uom4_id { get; set; }
        public Nullable<decimal> uom4_qty { get; set; }
        public string uom5_id { get; set; }
        public Nullable<decimal> uom5_qty { get; set; }
        public Nullable<decimal> uom1_price { get; set; }
        public Nullable<decimal> uom2_price { get; set; }
        public Nullable<decimal> uom3_price { get; set; }
        public Nullable<decimal> uom4_price { get; set; }
        public Nullable<decimal> uom5_price { get; set; }
    
        public virtual tb_product tb_product { get; set; }
    }
}
