//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_po_attachment
    {
        public string po_attachment_id { get; set; }
        public string po_attachment_name { get; set; }
        public string po_attachment_extension { get; set; }
        public string file_path { get; set; }
        public string po_id { get; set; }
    
        public virtual tb_purchase_order tb_purchase_order { get; set; }
    }
}
