//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_project()
        {
            this.tb_build_of_quantity = new HashSet<tb_build_of_quantity>();
            this.tb_item_request = new HashSet<tb_item_request>();
            this.tb_project_pm = new HashSet<tb_project_pm>();
            this.tb_site_manager_project = new HashSet<tb_site_manager_project>();
            this.tb_spacemen_attachment = new HashSet<tb_spacemen_attachment>();
            this.tb_stock_issue = new HashSet<tb_stock_issue>();
            this.tbSiteSiteSupervisors = new HashSet<tbSiteSiteSupervisor>();
        }
    
        public string project_id { get; set; }
        public string project_no { get; set; }
        public string project_short_name { get; set; }
        public string project_full_name { get; set; }
        public Nullable<System.DateTime> project_start_date { get; set; }
        public Nullable<System.DateTime> project_actual_start_date { get; set; }
        public Nullable<System.DateTime> project_end_date { get; set; }
        public Nullable<System.DateTime> project_actual_end_date { get; set; }
        public string project_address { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
        public string cutomer_id { get; set; }
        public string cutomer_signatory { get; set; }
        public string cutomer_project_manager { get; set; }
        public string site_id { get; set; }
        public string project_manager { get; set; }
        public string site_manager_1 { get; set; }
        public string site_manager_2 { get; set; }
        public Nullable<bool> project_status { get; set; }
        public string project_telephone { get; set; }
        public string customer_telephone { get; set; }
        public string p_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_build_of_quantity> tb_build_of_quantity { get; set; }
        public virtual tb_customer tb_customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_item_request> tb_item_request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_project_pm> tb_project_pm { get; set; }
        public virtual tb_site tb_site { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_site_manager_project> tb_site_manager_project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_spacemen_attachment> tb_spacemen_attachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_stock_issue> tb_stock_issue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSiteSiteSupervisor> tbSiteSiteSupervisors { get; set; }
    }
}
