//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_po_report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_po_report()
        {
            this.tb_purchase_request_detail = new HashSet<tb_purchase_request_detail>();
        }
    
        public string po_report_id { get; set; }
        public string po_report_number { get; set; }
        public string po_ref_id { get; set; }
        public string po_supplier_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<bool> vat_status { get; set; }
        public bool is_completed { get; set; }
        public Nullable<bool> is_lpo { get; set; }
        public string po_report_status { get; set; }
        public Nullable<bool> is_invoice { get; set; }
    
        public virtual tb_purchase_order tb_purchase_order { get; set; }
        public virtual tb_supplier tb_supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_purchase_request_detail> tb_purchase_request_detail { get; set; }
    }
}
