//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_purchase_request_detail
    {
        public string pr_detail_id { get; set; }
        public string purchase_request_id { get; set; }
        public string po_report_id { get; set; }
        public string status { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> vat_amount { get; set; }
        public Nullable<decimal> amount_before_vat { get; set; }
        public Nullable<decimal> outstanding_amount { get; set; }
    
        public virtual tb_po_report tb_po_report { get; set; }
        public virtual tb_purchase_request tb_purchase_request { get; set; }
    }
}
