//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_product()
        {
            this.tb_ir_detail2 = new HashSet<tb_ir_detail2>();
            this.tb_multiple_uom = new HashSet<tb_multiple_uom>();
            this.tb_product_detail = new HashSet<tb_product_detail>();
            this.tb_purchase_requisition_detail = new HashSet<tb_purchase_requisition_detail>();
            this.tb_received_item_detail = new HashSet<tb_received_item_detail>();
            this.tb_stock_transfer_detail = new HashSet<tb_stock_transfer_detail>();
        }
    
        public string product_id { get; set; }
        public string product_code { get; set; }
        public string product_name { get; set; }
        public string product_unit { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
        public string group_id { get; set; }
        public string product_type_id { get; set; }
        public string brand_id { get; set; }
        public string product_class_id { get; set; }
        public string product_size_id { get; set; }
        public string model_factory_code { get; set; }
        public string supplier_id { get; set; }
        public string labor_hour { get; set; }
        public string insulation_color { get; set; }
        public string sheath_color { get; set; }
        public string number_of_core { get; set; }
        public string outer_sheath { get; set; }
        public string color { get; set; }
        public string product_size { get; set; }
        public string product_category_id { get; set; }
        public string sub_group_id { get; set; }
        public Nullable<decimal> labour_hour { get; set; }
        public string so_number { get; set; }
        public string cash_flow { get; set; }
        public Nullable<decimal> product_number { get; set; }
    
        public virtual tb_brand tb_brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ir_detail2> tb_ir_detail2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_multiple_uom> tb_multiple_uom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_product_detail> tb_product_detail { get; set; }
        public virtual tb_product_class tb_product_class { get; set; }
        public virtual tb_product_size tb_product_size { get; set; }
        public virtual tb_supplier tb_supplier { get; set; }
        public virtual tb_unit tb_unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_purchase_requisition_detail> tb_purchase_requisition_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_received_item_detail> tb_received_item_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_stock_transfer_detail> tb_stock_transfer_detail { get; set; }
    }
}
