//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product_detail
    {
        public string p_detail_id { get; set; }
        public Nullable<decimal> p_detail_unit_price { get; set; }
        public string site_id { get; set; }
        public string supplier_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public string product_id { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
    
        public virtual tb_product tb_product { get; set; }
        public virtual tb_site tb_site { get; set; }
        public virtual tb_supplier tb_supplier { get; set; }
    }
}
