//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_po_supplier
    {
        public string po_supplier_id { get; set; }
        public string po_detail_id { get; set; }
        public string supplier_id { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<bool> is_selected { get; set; }
        public string Reason { get; set; }
        public string sup_number { get; set; }
        public Nullable<decimal> po_qty { get; set; }
        public Nullable<bool> vat { get; set; }
        public Nullable<bool> is_check { get; set; }
        public Nullable<decimal> original_price { get; set; }
        public Nullable<decimal> discount_percentage { get; set; }
        public Nullable<decimal> discount_amount { get; set; }
        public Nullable<decimal> lumpsum_discount_amount { get; set; }
    
        public virtual tb_purchase_order_detail tb_purchase_order_detail { get; set; }
        public virtual tb_supplier tb_supplier { get; set; }
    }
}
