//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_po_invoice
    {
        public string invoice_id { get; set; }
        public string po_report_id { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public string invoice_number_shipper { get; set; }
        public string invoice_number_forwarder { get; set; }
        public Nullable<decimal> invoice_amount { get; set; }
        public Nullable<decimal> invoice_vat_amount { get; set; }
        public Nullable<decimal> transporation_fee { get; set; }
        public Nullable<decimal> import_duty { get; set; }
        public Nullable<decimal> paid_amount { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<bool> is_active { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string craeted_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string updated_by { get; set; }
    }
}
