//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_purchase_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_purchase_order()
        {
            this.tb_po_attachment = new HashSet<tb_po_attachment>();
            this.tb_po_report = new HashSet<tb_po_report>();
            this.tb_purchase_order_detail = new HashSet<tb_purchase_order_detail>();
        }
    
        public string purchase_order_id { get; set; }
        public string purchase_oder_number { get; set; }
        public string item_request_id { get; set; }
        public string purchase_order_status { get; set; }
        public Nullable<decimal> shipping_price { get; set; }
        public Nullable<bool> vat { get; set; }
        public Nullable<bool> status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string checked_by { get; set; }
        public Nullable<System.DateTime> checked_date { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public bool is_completed { get; set; }
        public string pol_project_short_name_number { get; set; }
        public string shipping_to { get; set; }
        public Nullable<bool> is_po_checked { get; set; }
        public string od_checked_by { get; set; }
        public Nullable<System.DateTime> od_checked_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_po_attachment> tb_po_attachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_po_report> tb_po_report { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_purchase_order_detail> tb_purchase_order_detail { get; set; }
        public virtual tb_purchase_requisition tb_purchase_requisition { get; set; }
    }
}
