//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_quote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_quote()
        {
            this.tb_quote_detail = new HashSet<tb_quote_detail>();
        }
    
        public string quote_id { get; set; }
        public string quote_no { get; set; }
        public string supplier_id { get; set; }
        public Nullable<bool> is_selected { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string updated_by { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public string approved_comment { get; set; }
        public string checked_by { get; set; }
        public Nullable<System.DateTime> checked_date { get; set; }
        public string checked_comment { get; set; }
        public string quote_status { get; set; }
        public string mr_id { get; set; }
        public string incoterm { get; set; }
        public string payment { get; set; }
        public string delivery { get; set; }
        public string shipment { get; set; }
        public string warranty { get; set; }
        public string vendor_ref { get; set; }
        public Nullable<decimal> grand_total_amount { get; set; }
        public Nullable<decimal> lump_sum_discount_amount { get; set; }
    
        public virtual tb_purchase_requisition tb_purchase_requisition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_quote_detail> tb_quote_detail { get; set; }
        public virtual tb_supplier tb_supplier { get; set; }
    }
}
