//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_reject
    {
        public string reject_id { get; set; }
        public string ref_id { get; set; }
        public string ref_type { get; set; }
        public string comment { get; set; }
        public string rejected_by { get; set; }
        public Nullable<System.DateTime> rejected_date { get; set; }
    }
}
