//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_return_mainstock_detail
    {
        public string main_stock_detail_id { get; set; }
        public string main_stock_detail_ref { get; set; }
        public string main_stock_detail_item { get; set; }
        public string main_stock_warehouse_id { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public string remark { get; set; }
        public string supplier_id { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> previous_quantity { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public string item_status { get; set; }
        public string invoice_number { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public string main_stock_detail_type { get; set; }
        public Nullable<decimal> remain_quantity { get; set; }
    
        public virtual tb_return_main_stock tb_return_main_stock { get; set; }
    }
}
