//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_received_status
    {
        public string received_status_id { get; set; }
        public string received_id { get; set; }
        public string received_ref_id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    }
}
