//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_received_item_detail
    {
        public string ri_detail_id { get; set; }
        public string ri_ref_id { get; set; }
        public string ri_item_id { get; set; }
        public string ri_warehouse_id { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public string unit { get; set; }
        public string invoice_number { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public string supplier_id { get; set; }
        public string item_status { get; set; }
        public string remark { get; set; }
        public bool completed { get; set; }
    
        public virtual tb_product tb_product { get; set; }
        public virtual tb_receive_item_voucher tb_receive_item_voucher { get; set; }
        public virtual tb_warehouse tb_warehouse { get; set; }
    }
}
