//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_return_main_stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_return_main_stock()
        {
            this.tb_return_mainstock_detail = new HashSet<tb_return_mainstock_detail>();
        }
    
        public string return_main_stock_id { get; set; }
        public string return_main_stock_no { get; set; }
        public string return_type { get; set; }
        public string return_ref_id { get; set; }
        public string return_main_stock_status { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string update_by { get; set; }
        public string approved_by { get; set; }
        public string last_approved_by { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public string checked_by { get; set; }
        public Nullable<System.DateTime> checked_date { get; set; }
        public string checked_comment { get; set; }
        public string completed_by { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public string completed_comment { get; set; }
        public Nullable<bool> is_receive_completed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_return_mainstock_detail> tb_return_mainstock_detail { get; set; }
    }
}
