//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_system_menu_action
    {
        public int action_id { get; set; }
        public Nullable<int> menu_id { get; set; }
        public string action_type { get; set; }
        public string url { get; set; }
        public string controller_name { get; set; }
        public string action_name { get; set; }
        public string comment { get; set; }
        public Nullable<bool> keepAlive { get; set; }
    }
}
