//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_stock_adjustment
    {
        public string stock_adjustment_id { get; set; }
        public string stock_adjuctment_code { get; set; }
        public string warehouse_id { get; set; }
        public string comment { get; set; }
        public string stock_adjustment_status { get; set; }
        public Nullable<bool> status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public string checked_by { get; set; }
        public Nullable<System.DateTime> checked_date { get; set; }
        public string checked_comment { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public string completed_by { get; set; }
        public string completed_comment { get; set; }
    
        public virtual tb_warehouse tb_warehouse { get; set; }
    }
}
