//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_supplier()
        {
            this.tb_po_report = new HashSet<tb_po_report>();
            this.tb_po_supplier = new HashSet<tb_po_supplier>();
            this.tb_product = new HashSet<tb_product>();
            this.tb_product_detail = new HashSet<tb_product_detail>();
            this.tb_quote = new HashSet<tb_quote>();
        }
    
        public string supplier_id { get; set; }
        public string supplier_name { get; set; }
        public string supplier_contact_person { get; set; }
        public string supplier_phone { get; set; }
        public string supplier_email { get; set; }
        public string supplier_address { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> is_local { get; set; }
        public string supplier_type { get; set; }
        public string supplier_fax { get; set; }
        public string incoterm { get; set; }
        public string payment { get; set; }
        public string delivery { get; set; }
        public string shipment { get; set; }
        public string warranty { get; set; }
        public string vendor_ref { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_po_report> tb_po_report { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_po_supplier> tb_po_supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_product> tb_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_product_detail> tb_product_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_quote> tb_quote { get; set; }
    }
}
