//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_spacemen_attachment
    {
        public string spacemen_att_id { get; set; }
        public string spacemen_filename { get; set; }
        public string spacemen_extension { get; set; }
        public string file_path { get; set; }
        public string project_id { get; set; }
    
        public virtual tb_project tb_project { get; set; }
    }
}
