//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user_detail
    {
        public string user_detail_id { get; set; }
        public string user_id { get; set; }
        public string user_first_name { get; set; }
        public string user_last_name { get; set; }
        public string user_position_id { get; set; }
        public string user_telephone { get; set; }
        public string user_email { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
        public string user_signature { get; set; }
    
        public virtual tb_position tb_position { get; set; }
    }
}
