//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_warehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_warehouse()
        {
            this.tb_invoice = new HashSet<tb_invoice>();
            this.tb_received_item_detail = new HashSet<tb_received_item_detail>();
            this.tb_stock_adjustment = new HashSet<tb_stock_adjustment>();
            this.tb_stock_keeper_warehouse = new HashSet<tb_stock_keeper_warehouse>();
            this.tb_stock_transfer_detail = new HashSet<tb_stock_transfer_detail>();
            this.tb_stock_transfer_voucher = new HashSet<tb_stock_transfer_voucher>();
            this.tb_warehouse_qaqc = new HashSet<tb_warehouse_qaqc>();
        }
    
        public string warehouse_id { get; set; }
        public string warehouse_name { get; set; }
        public string warehouse_telephone { get; set; }
        public string warehouse_address { get; set; }
        public string warehouse_site_id { get; set; }
        public Nullable<bool> warehouse_status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string warehouse_project_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_invoice> tb_invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_received_item_detail> tb_received_item_detail { get; set; }
        public virtual tb_site tb_site { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_stock_adjustment> tb_stock_adjustment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_stock_keeper_warehouse> tb_stock_keeper_warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_stock_transfer_detail> tb_stock_transfer_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_stock_transfer_voucher> tb_stock_transfer_voucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_warehouse_qaqc> tb_warehouse_qaqc { get; set; }
    }
}
