//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_warehouse_qaqc
    {
        public string warehouse_qaqc_id { get; set; }
        public string warehouse_id { get; set; }
        public string qaqc_id { get; set; }
    
        public virtual tb_warehouse tb_warehouse { get; set; }
    }
}
