//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_KimMex.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class transferformmainstock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public transferformmainstock()
        {
            this.tb_transfer_frommain_stock_detail = new HashSet<tb_transfer_frommain_stock_detail>();
        }
    
        public string stock_transfer_id { get; set; }
        public string stock_transfer_no { get; set; }
        public string stock_transfer_status { get; set; }
        public string item_request_id { get; set; }
        public Nullable<bool> status { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> checked_date { get; set; }
        public string checked_by { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public string approved_by { get; set; }
        public Nullable<bool> is_completed { get; set; }
        public string checked_comment { get; set; }
        public string completed_by { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public string completed_comment { get; set; }
        public Nullable<bool> is_receive_completed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_transfer_frommain_stock_detail> tb_transfer_frommain_stock_detail { get; set; }
    }
}
